{{ if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly.fullname" . }}-secret
  labels:
{{ include "firefly.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.secrets.admin_password }}
  "ADMIN_PASSWORD": "{{ .Values.secrets.admin_password }}"
{{- else }}
  "ADMIN_PASSWORD": "{{ randAlphaNum 32 | b64enc }}"
{{- end }}
{{ end }}
